### ISSUE TITLE
Avoid using OWASP in the name of as it is a trademark owned by OWASP

### ISSUE THREAD

**Issue by securestep9** [AlexGitHub11/Wasp-Web#1]
Important note: The use of "OWASP" as a name for a game or vulnerable app may infringe on the trademark of The OWASP Foundation. To avoid legal issues, please consider the following:

The OWASP Foundation has established name usage guidelines, which can be found on their website: https://owasp.org/www-policy/operational/mark-usage-guidelines

It's acceptable to describe your game or app as a tool for testing OWASP Top 10 knowledge. However, it's not permissible to name it "OWASP Web" as it could misrepresent OWASP as an official project. Instead, choose a distinctive name, such as "VulnWeb," and then consider registering your project with the OWASP Foundation as an OWASP project. This would allow you to use the "OWASP" prefix, for example, "OWASP VulnWeb." Be mindful that "Web" may sound too generic, so consider a more descriptive name.

For inspiration, explore the directory of similar projects on the OWASP website: https://owasp.org/www-project-vulnerable-web-applications-directory/

**Comment by AlexGitHub11** [comment]
Dear Sam.

Thank you for your important note regarding the use of the "OWASP" name for
my project.

I have taken your advice and changed the project name to avoid using
"OWASP" in the title. Additionally, I will update the README file to
clearly distinguish that the project is inspired by OWASP but has no
official affiliation with the OWASP Foundation.

Specifically, the README will now include a statement acknowledging OWASP
as the inspiration for the project, along with a disclaimer that this
project is not affiliated with or endorsed by the OWASP Foundation.

Thank you again for bringing this to my attention and guiding me through
the necessary steps. Please let me know if there are any additional actions
I should take to ensure full compliance.

Best regards,

Alex.
